version: 2

before:
  hooks:
    - go mod tidy
    - ./bin/completions.sh
    - ./bin/manpages.sh
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X main.VERSION={{.Version}}
      - -X main.LASTMOD={{.Timestamp}}
      - -X main.COMMIT={{.ShortCommit}}
      - -X main.BUILTBY=goreleaser
    main: ./cmd/fflint/main.go
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [ tar.gz ]
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [ zip ]
    files:
      - src: README.md
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE.txt
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: completions/*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: manpages/*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

homebrew_casks:
  - name: fflint
    binaries:
      - fflint
    manpages:
      - manpages/fflint.1.gz
    completions:
      bash: completions/fflint.bash
      zsh: completions/fflint.zsh
      fish: completions/fflint.fish
    directory: Casks
    skip_upload: false
    description: "File formt linter"
    homepage: "https://www.fflint.dev/"
    license: "MIT"
    repository:
      owner: FileFormatInfo
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fflint"]
          end

