# documentation lives at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - ./bin/completions.sh
    - ./bin/manpages.sh
    #- go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/badger
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE.txt
      - completions/*
      - manpages/*
brews:
# - tap:
#     owner: fileformat
#     name: homebrew-tap
#   folder: Formula
#   homepage: https://www.badger.sh
#   description: badger is file format linter for SVG, markdown, frontmatter, JSON and more.
#   license: AGPL-3.0
#   test: |
#     system "#{bin}/badger -v"
#   install: |-
#     bin.install "badger"
#     bash_completion.install "completions/badger.bash" => "badger"
#     zsh_completion.install "completions/badger.zsh" => "_badger"
#     fish_completion.install "completions/badger.fish"
#     man1.install "manpages/badger.1.gz"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
