name: 'File Format Badger'
description: 'Badger you about your file formats''
inputs:
  cmd:
    description: 'command to run'
    required: true
    default: 'version'
  options:
    description: 'options for this command'
    required: false
    default: ''
  files:
    description: 'files to check'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'


