#
# _config.yml for www.fflint.dev
#

collections:
  commands:
    output: true
exclude: [ "CNAME" ]
permalink: /blog/:year/:month/:day/:title/index.:output_ext
production_url: https://www.fflint.dev
title: fflint
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..3
markdown: kramdown
plugins:
  - jekyll-redirect-from
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
#sass_dir: "./_sass"
