#
# _config.yml for emoji.fileformat.info
#

exclude: [ "CNAME" ]
permalink: /blog/:year/:month/:day/:title/index.:output_ext
production_url: https://www.badger.sh
title: Badger
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..3
markdown: kramdown
plugins:
  - jekyll-redirect-from
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
#sass_dir: "./_sass"
