name: "Dogfooding"

# Why is this called "dogfooding"? https://en.wikipedia.org/wiki/Eating_your_own_dog_food

on:
  push:

  workflow_dispatch:

jobs:
  dogfooding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: |
          go build -o ./badger cmd/badger/main.go

      - name: Check favicon.ico
        run: |
          ./badger ico --show-tests=all docs/favicon.ico

      - name: Check markdown frontmatter
        run: |
          ./badger frontmatter --required=title "docs/**/*.md"

      # LATER: build website w/Jekyll and test the generated files

      - name: Generate reports
        run: |
          echo "# Badgering the badger" >$GITHUB_STEP_SUMMARY
          echo "## Extensions in use" >>$GITHUB_STEP_SUMMARY
          ./badger ext --output=markdown "./**" >>$GITHUB_STEP_SUMMARY
          echo "" >>$GITHUB_STEP_SUMMARY
          echo "## Content types in use" >>$GITHUB_STEP_SUMMARY
          ./badger mimetype --output=markdown "./**" >>$GITHUB_STEP_SUMMARY
